### ISSUE TITLE
文件在浏览器中查看 中文全部乱码

### ISSUE THREAD

**Issue by buffge** [demon90s/CppStudy#1]
返回头中加一个 Content-Type: text/plain; charset=utf-8 应该就可以了.
但是我不知道github.io 可不可以加.
错误页面: https://demon90s.github.io/CppStudy/codes/CppPrimer/ch18_Tools_for_Large_Programs/exercise_18_01.cpp

**Comment by demon90s** [comment]
是啊，是有这样的问题。还是在编辑器中浏览比较舒服。
谢谢
